name: BILLY
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  # TRIVY:
    # name: TRIVY
    # runs-on: ubuntu-latest
    # steps:
      # - name: Checkout code
        # uses: actions/checkout@v2

      # - name: Aqua code scanning (SCA,IaC and SAST)
        # uses: docker://aquasec/aqua-scanner
        # with:
         # args: trivy fs --sast --reachability --scanners misconfig,vuln,secret --db-repository=registry.aquasec.com/trivy-db:2 --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 --java-db-repository=registry.aquasec.com/trivy-java-db:1 /github/workspace

        # env:
          # # OVERRIDE_RUN_ID: 696969
          # ENABLE_TRIVY_STDOUT: 'true'
          # TRIVY_USERNAME: ${{ secrets.AQUADEV_USERNAME }}
          # TRIVY_PASSWORD: ${{ secrets.AQUADEV_PASS }}
          # AQUA_KEY: ${{ secrets.AQUA_KEY }}
          # AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          # GITHUB_TOKEN: ${{ github.token }}
          # AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
          # CSPM_URL: https://eu-1.api.cloudsploit.com
          # TRIVY_RUN_AS_PLUGIN: 'aqua'

  BILLY:
    name: BILLY
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t aquasupportemea/insecure-bank-app:${{ github.sha }} .

      - name: SBOM Generation - Manifest Generation
        run: |
          # export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
          # curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          # curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          # if ! cat install.sh.checksum | sha256sum --check; then
          # echo "install.sh checksum failed"
          # exit 1
          # fi
          # BINDIR="." sh install.sh
          # rm install.sh install.sh.checksum
          # # export OVERRIDE_RUN_ID=696969
          # # ./billy generate \
            # # --access-token "${{ secrets.GITHUB_TOKEN }}" \
            # # --aqua-key "${{ secrets.AQUA_KEY }}" \
            # # --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            # # --cspm-url https://eu-1.api.cloudsploit.com \
            # # --artifact-path "aquasupportemea/insecure-bank-app:${{ github.sha }}"
          # ./billy health \
            # --access-token "${{ secrets.GITHUB_TOKEN }}" \
            # --aqua-key "${{ secrets.AQUA_KEY }}" \
            # --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            # --cspm-url https://eu-1.api.cloudsploit.com \
            # --artifact-path "aquasupportemea/insecure-bank-app:${{ github.sha }}"
          docker image ls

      - name: Aqua Image Scanner
        uses: mulan04/aqua-actions/Aqua_Image_Scanner@v1
        with:
          registry: registry.aquasec.com
          username: ${{ secrets.AQUA_USERNAME }}
          password: ${{ secrets.AQUA_PASSWORD }}
          scanner_image: scanner
          tag: "10"
          run_args: "-v /var/run/docker.sock:/var/run/docker.sock \
		             -v /tmp:/tmp \
					 -e BUILD_URL=${{ GITHUB_SERVER_URL }}/${{ GITHUB_REPOSITORY }}/actions/runs/${{ GITHUB_RUN_ID }} \
					 -e BUILD_NUMBER=${{ github.sha }}"
          scan_args: "--local aquasupportemea/insecure-bank-app:${{ github.sha }} \
                      --host ${{ secrets.AQUA_HOST }} \
                      --token ${{ secrets.AQUA_TOKEN }} \
                      --layer-vulnerabilities \
                      --jsonfile /tmp/out.json --htmlfile /tmp/out.html"

      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Aqua Scan Report
          path: |
            /tmp/out.html
            /tmp/out.json